#!/bin/csh

set c_file = main.c
set work_dir = .
set C_DIR = /mnt/data2/hongyu/EQTime/Maligaro/c_lib


set my_lib = $C_DIR
set tool_lib = $my_lib/c01_tools
set ESF_lib = $my_lib/c02_empirical_wavelet

##set INFILE = $work_dir/INFILE
##set sachome = `grep -w SACHOME $INFILE |awk '{print $2}'`
set sachome = $SACHOME


# make a library file from c file
gcc -c $tool_lib/*.c -I$tool_lib    -lsacio -L$sachome/lib -lm -I$sachome/include
gcc -c $ESF_lib/*.c -I$ESF_lib  -I$tool_lib  -L$sachome/lib -I$sachome/include -lsacio  -lm 



ar cr libHongyu.a *.o
gcc   $c_file -I$tool_lib -I$ESF_lib   -L./ -lHongyu  -lm -m64    -Wno-unused   -L$sachome/lib -I$sachome/include -lsacio -lm


rm *.o *.a
exit 0 
